server:
  port: 8090

spring:
  application:
    name: auth
  datasource:
    url: jdbc:mysql://localhost:3306/stu_sys?characterEncoding=utf8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    hikari:
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-lifetime: 86430000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl